############################
## CHANGE THESE
############################

baseURL: 'https://djegoblog.org/'
title: 'El blog de Diego'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'es-es'
enableRobotsTXT: true

markup:
  _merge: deep
