############################
## Author
############################

author:
author:
  name: 'El blog de Diego'
  image: author.png
  greeting: 'Un blog personal donde escribo, mi peque침o rinc칩n en Internet'
  icon: 

############################
## Links
############################

links:
  - artstation: https://djego.artstation.com/
  # github:  
  # - gitlab:
  # facebook:
  # - x-twitter:
  # - mastodon:
  # linkedin:
  # instagram:
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  - email: mailto:djegogutjerrez@gmail.com
  # website:
  # - link:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  - bluesky: https://bsky.app/profile/djegoblog.org
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  - amazon: https://www.amazon.es/stores/Diego-Guti%C3%A9rrez-Ferrero/author/B0CHY35KY5
  # - google:
  # - paypal:
  # - pgp-key:
  # - windows:
  # - codeberg:
  # - pixelfed:
  # - substack:
  # - newsletter:

###############################
## OpenGraph & Twitter Cards
###############################

title: 'El blog de Diego'
description: 'Un blog personal donde escribo, mi peque침o rinc칩n en Internet'
images:
  - thumbnail.png

###############################
## Latex math
###############################

# To configure Latex rendering on all pages, change to: true
#
# To only add Latex rendering on pages that need it, set in the frontmatter
# of each page that needs it:
#   params:
#     math: true
# This option will allow better performance, as it'll only load
# the extra JS when needed.
math: false
